version: '2'
services:
  app:
    build: ./docker/app
    container_name: python-app-container
    ports: 
      - 5000:5000
    volumes: 
      - ./app:/app
  webpack:
    build: ./docker/webpack
    container_name: webpack-container
    ports:
      - 35729:35729
    volumes:
      - /app/node_modules
      - ./app:/app
